name: Node CI
on: [push,]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest Code
      uses: actions/checkout@v3
      with:
        path: sass-backend

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install npm dependencies
      run: cd sass-backend &&  npm install

    - name: Run build task
      run: cd sass-backend &&  npm run build --if-present

    - name: Copy files to Server
      uses: appleboy/scp-action@master
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "sass-backend,!sass-backend/.git,!sass-backend/.github"
        overwrite: true
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: ${{ secrets.HOST_PORT }}
        target: ${{ secrets.REMOTE_TARGET }}
        
    - name: Deploy code to Server
      uses: appleboy/ssh-action@master
      with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # source: "sass-backend"
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.HOST_PORT }}
          # target: ${{ secrets.REMOTE_TARGET }}
          script: |
            cd ~/apps/sass-backend
            docker compose up --build -d
      


